/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "check_test.check" instead.
 */

#include <check.h>

#line 1 "check_test.check"
#include <check.h>
#include <locale.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

#define CHK_EPS 1e-6

// 0., -0., 1., -1., 1e-4, 1e4, -1e-4, -1e4, S21_MAX_DOUBLE, S21_NAN, S21_INF,
// -S21_INF



START_TEST(fabs_basic)
{
#line 18

double testcases[] = {
    1e-10,          -1e-10,         0.5, -0.5, 1., -1., 1e-4, 1e4, -1e-4, -1e4,
    S21_MAX_DOUBLE, -S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_eq_tol(s21_fabs(testcases[i]), fabs(testcases[i]), CHK_EPS);

}
END_TEST

START_TEST(fabs_inf)
{
#line 28

double testcases[] = {S21_INF, -S21_INF};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_infinite(s21_fabs(testcases[i]));

}
END_TEST

START_TEST(fabs_nan)
{
#line 36

ck_assert_ldouble_nan(s21_fabs(S21_NAN));

}
END_TEST

START_TEST(fact_test)
{
#line 42

int testcases[] = {1, 2, 5, 10};
int result[] = {1, 2, 120, 3628800};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_int_eq(s21_fact(testcases[i]), result[i]);

}
END_TEST


START_TEST(fmod_basic)
{
#line 55

double testcases[] = {
    1e-10,          -1e-10,         0.5, -0.5, 1., -1., 1e-4, 1e4, -1e-4, -1e4,
    S21_MAX_DOUBLE, -S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  for (size_t j = 0; j < n; ++j)
    ck_assert_ldouble_eq_tol(s21_fmod(testcases[i], testcases[j]),
                             fmod(testcases[i], testcases[j]), CHK_EPS);

}
END_TEST

START_TEST(fmod_basic_inf)
{
#line 67

double testcases[] = {
    1e-10,          -1e-10,         0.5, -0.5, 1., -1., 1e-4, 1e4, -1e-4, -1e4,
    S21_MAX_DOUBLE, -S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  for (size_t j = 0; j < n; ++j)
    ck_assert_ldouble_eq_tol(s21_fmod(testcases[i], S21_INF),
                             fmod(testcases[i], S21_INF), CHK_EPS);

}
END_TEST

START_TEST(fmod_nan)
{
#line 79

double testcases[] = {
    1e-10,          -1e-10,         0.5, -0.5, 1., -1., 1e-4, 1e4, -1e-4, -1e4,
    S21_MAX_DOUBLE, -S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  for (size_t j = 0; j < n; ++j) {
    ck_assert_ldouble_nan(s21_fmod(testcases[i], 0));
    ck_assert_ldouble_nan(s21_fmod(S21_NAN, testcases[i]));
    ck_assert_ldouble_nan(fmod(S21_NAN, testcases[i]));
  }

}
END_TEST


START_TEST(exp_basic)
{
#line 97

double testcases[] = {1e-10, -1e-10, -19, 0.5,   -0.5, 1.,
                      -1.,   1e-4,   3e2, -1e-4, -1e4, -S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  long double result = s21_exp(testcases[i]);
  double expected_result = exp(testcases[i]);
  if (result > 1e16) {
    int power = ceil(log10l(result));
    result *= powl(10, 16 - power);
    result = truncl(result);

    power = ceil(log10l(expected_result));
    expected_result *= pow(10, 16 - power);
    expected_result = trunc(expected_result);
  }
  ck_assert_ldouble_eq_tol(result, expected_result, CHK_EPS);
}

}
END_TEST

START_TEST(exp_inf)
{
#line 118

double testcases[] = {1e4, 1e10, S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_infinite(s21_exp(testcases[i]));
  ck_assert_ldouble_infinite(exp(testcases[i]));
}

}
END_TEST

START_TEST(exp_nan)
{
#line 128
ck_assert_ldouble_nan(s21_exp(S21_NAN));
ck_assert_ldouble_nan(exp(S21_NAN));

}
END_TEST

START_TEST(log_basic)
{
#line 134

double testcases[] = {1e-10,      1e-4, 0.5,           1., 1.5, 100,
                      9.123123e6, 1e4,  S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  for (size_t j = 0; j < n; ++j)
    ck_assert_ldouble_eq_tol(s21_log(testcases[i]), log(testcases[i]), CHK_EPS);

}
END_TEST

START_TEST(log_inf)
{
#line 144

double testcases[] = {0, S21_INF};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_infinite(s21_log(testcases[i]));
  ck_assert_ldouble_infinite(log(testcases[i]));
}

}
END_TEST

START_TEST(log_nan)
{
#line 154

double testcases[] = {-S21_MAX_DOUBLE, -1e4, -1, S21_NAN};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_nan(s21_log(testcases[i]));
  ck_assert_ldouble_nan(log(testcases[i]));
}

}
END_TEST

START_TEST(pow_basic)
{
#line 166
double testcases[] = {1., 2., 3., 4., 5., 10., 1e-10, 1e-5, 0.5, 0.1, 24.536};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  for (size_t j = 0; j < n; ++j)
    for (int sgn = 1; sgn <= 1; sgn += 2) {
      // printf("%.16lf\t%.16lf\t%d\n", testcases[i], testcases[j], sgn);

      long double result = s21_pow(testcases[i], testcases[j] * sgn);
      double expected_result = pow(testcases[i], testcases[j] * sgn);
      if (result > 1e10) {
        int power = ceil(log10l(result));
        result *= powl(10, 10 - power);
        result = truncl(result);

        power = ceil(log10l(expected_result));
        expected_result *= pow(10, 10 - power);
        expected_result = trunc(expected_result);

        
      }
      // printf("%.6Lf\n%.6lf\n", result, expected_result);
      ck_assert_ldouble_eq_tol(result, expected_result, CHK_EPS);
    }

}
END_TEST

START_TEST(test_s21_pow)
{
#line 192
    ck_assert_ldouble_eq(s21_pow(0, 0), pow(0, 0));
    ck_assert_ldouble_eq(s21_pow(0, -1), pow(0, -1));
    ck_assert_ldouble_eq(s21_pow(0, 1), pow(0, 1));
    ck_assert_ldouble_eq(s21_pow(1, 0), pow(1, 0));
    ck_assert_ldouble_eq(s21_pow(-1, 1), pow(-1, 1));
    ck_assert_ldouble_eq(s21_pow(-1, 2), pow(-1, 2));
    ck_assert_ldouble_eq(s21_pow(0.5, S21_INF), pow(0.5, S21_INF));
    ck_assert_ldouble_eq(s21_pow(0.5, -S21_INF), pow(0.5, -S21_INF));
    ck_assert_ldouble_eq(s21_pow(S21_NAN, 0), pow(S21_NAN, 0));
    ck_assert_ldouble_eq(s21_pow(S21_INF, 0), pow(S21_INF, 0));
    ck_assert_ldouble_eq(s21_pow(S21_INF, -1), pow(S21_INF, -1));
    ck_assert_ldouble_eq(s21_pow(0, S21_INF), pow(0, S21_INF));
    ck_assert_ldouble_eq(s21_pow(-1, -S21_INF), pow(-1, -S21_INF));
    ck_assert_ldouble_eq(s21_pow(1, -S21_INF), pow(1, -S21_INF));
    ck_assert_ldouble_eq(s21_pow(2, S21_INF), pow(2, S21_INF));
    ck_assert_ldouble_eq(s21_pow(-2, S21_INF), pow(-2, S21_INF));
    ck_assert_ldouble_eq(s21_pow(2, -S21_INF), pow(2, -S21_INF));
    ck_assert_ldouble_eq(s21_pow(-2, -S21_INF), pow(-2, -S21_INF));
    ck_assert_ldouble_eq(s21_pow(S21_INF, S21_INF), pow(S21_INF, S21_INF));
    ck_assert_ldouble_eq(s21_pow(S21_INF, -S21_INF), pow(S21_INF, -S21_INF));
    ck_assert_ldouble_eq(s21_pow(-S21_INF, S21_INF), pow(-S21_INF, S21_INF));
    ck_assert_ldouble_eq(s21_pow(-S21_INF, -S21_INF), pow(-S21_INF, -S21_INF));
    ck_assert_ldouble_nan(pow(-1.5, -2.5));
    ck_assert_ldouble_nan(s21_pow(-1.5, -2.5));
    ck_assert_ldouble_eq(s21_pow(-S21_INF, -3.), s21_pow(-S21_INF, -3.));
    ck_assert_ldouble_eq(s21_pow(-S21_INF, 3.), s21_pow(-S21_INF, 3.));
    ck_assert_ldouble_eq(s21_pow(5., 3.), s21_pow(5., 3.));
    ck_assert_ldouble_eq(s21_pow(5.5, -3.1), s21_pow(5.5, -3.1));

}
END_TEST

START_TEST(test_s21_sqrt)
{
#line 222
    ck_assert_ldouble_eq_tol(s21_sqrt(0.0), sqrt(0.0), 1e-6);
    ck_assert_ldouble_eq_tol(s21_sqrt(-0.0), sqrt(-0.0), 1e-6);
    ck_assert_ldouble_eq_tol(s21_sqrt(1), sqrt(1), 1e-6);
    ck_assert_ldouble_eq_tol(s21_sqrt(1.000), sqrt(1.000), 1e-6);
    ck_assert_ldouble_eq_tol(s21_sqrt(0.0100), sqrt(0.0100), 1e-6);
    ck_assert_ldouble_eq_tol(s21_sqrt(10e+12), sqrt(10e+12), 1e-6);
    ck_assert_ldouble_eq_tol(s21_sqrt(456.321e-12), sqrt(456.321e-12), 1e-6);
    ck_assert_ldouble_eq_tol(s21_sqrt(123321.321123), sqrt(123321.321123), 1e-6);
    ck_assert_ldouble_nan(sqrt(S21_NAN));
    ck_assert_ldouble_nan(s21_sqrt(S21_NAN)); 
    ck_assert_ldouble_infinite(sqrt(S21_INF));
    ck_assert_ldouble_infinite(s21_sqrt(S21_INF));

}
END_TEST

START_TEST(test_s21_sin)
{
#line 236
    ck_assert_ldouble_eq_tol(s21_sin(0), sin(0), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(0.0), sin(0.0), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(S21_PI / 2), sin(S21_PI / 2), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(S21_PI / 3), sin(S21_PI / 3), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(3 * S21_PI / 2), sin(3 * S21_PI / 2), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(2 * S21_PI), sin(2 * S21_PI), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(-2 * S21_PI), sin(-2 * S21_PI), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(-3 * S21_PI), sin(-3 * S21_PI), 1e-06);
    ck_assert_ldouble_eq_tol(s21_sin(-S21_PI), sin(-S21_PI), 1e-06);
    
}
END_TEST

START_TEST(test_s21_cos)
{
#line 247
    ck_assert_float_eq(s21_cos(0), cos(0));
    ck_assert_float_eq(s21_cos(-1), cos(-1));
    ck_assert_ldouble_eq_tol(s21_cos(0), cos(0), 1e-06);
    ck_assert_ldouble_eq_tol(s21_cos(-1), cos(-1), 1e-06);
    ck_assert_ldouble_eq_tol(s21_cos(S21_PI), cos(M_PI), 1e-06);
    ck_assert_ldouble_eq_tol(s21_cos(S21_PI * 3.0 / 2.0), cos(M_PI * 3.0 / 2.0), 1e-06);
    ck_assert_ldouble_nan(cos(-S21_INF)); 
    ck_assert_ldouble_nan(s21_cos(-S21_INF));
    ck_assert_ldouble_nan(cos(S21_INF));
    ck_assert_ldouble_nan(s21_cos(S21_INF));
    ck_assert_ldouble_nan(cos(S21_NAN)); 
    ck_assert_ldouble_nan(s21_cos(S21_NAN));

}
END_TEST

START_TEST(test_s21_fmod)
{
#line 261
    ck_assert_ldouble_eq(s21_fmod(-7.77, -3.0), fmod(-7.77, -3.0));
    ck_assert_ldouble_eq(s21_fmod(-7.66, 2.0), fmod(-7.66, 2.0));
    ck_assert_ldouble_eq(s21_fmod(7.22, -1.0), fmod(7.22, -1.0));
    ck_assert_ldouble_eq(s21_fmod(9.46, 5.0), fmod(9.46, 5.0));
    ck_assert_ldouble_eq(s21_fmod(-12345, -7), fmod(-12345, -7));
    ck_assert_ldouble_eq(s21_fmod(-7, -54321), fmod(-7, -54321));
    ck_assert_ldouble_eq(s21_fmod(-23.15, 3), fmod(-23.15, 3));
    ck_assert_ldouble_eq(s21_fmod(5, -53.54), fmod(5, -53.54));
    ck_assert_ldouble_eq(s21_fmod(33.54, 2), fmod(33.54, 2));
    ck_assert_ldouble_eq(s21_fmod(3, 33.45), fmod(3, 33.45));
    ck_assert_ldouble_eq(s21_fmod(67890, 5), fmod(67890, 5));
    ck_assert_ldouble_eq(s21_fmod(-5, -5), fmod(-5, -5));
    // ck_assert_ldouble_eq_tol(s21_atan(-1.0 / 0.0), atan(-1.0 / 0.0), 1e-6);
    // ck_assert_ldouble_eq_tol(s21_atan(1.0 / 0.0), atan(1.0 / 0.0), 1e-6);
    ck_assert_ldouble_nan(fmod(1. / 0., 2.));
    ck_assert_ldouble_nan(s21_fmod(1. / 0., 2.));

}
END_TEST

START_TEST(test_s21_ceil)
{
#line 279
    ck_assert_ldouble_eq(s21_ceil(0), ceil(0));
    ck_assert_ldouble_eq(s21_ceil(0.0), ceil(0.0));
    ck_assert_ldouble_eq(s21_ceil(-0.0), ceil(-0.0));
    ck_assert_ldouble_eq(s21_ceil(-0.12), ceil(-0.12));
    ck_assert_ldouble_eq(s21_ceil(21.21), ceil(21.21));
    ck_assert_ldouble_eq(s21_ceil(-21.21), ceil(-21.21));
    ck_assert_ldouble_eq(s21_ceil(-32.99), ceil(-32.99));
    ck_assert_ldouble_eq(s21_ceil(-7.000000), ceil(-7.000000));
    ck_assert_ldouble_infinite(ceil(1.0 / 0.0));
    ck_assert_ldouble_infinite(s21_ceil(1.0 / 0.0));

}
END_TEST

START_TEST(test_s21_floor)
{
#line 291
    ck_assert_ldouble_eq(s21_floor(0), floor(0));
    ck_assert_ldouble_eq(s21_floor(-0), floor(-0));
    ck_assert_ldouble_eq(s21_floor(7.00000), floor(7.00000));
    ck_assert_ldouble_eq(s21_floor(-7.00000), floor(-7.00000));
    ck_assert_ldouble_eq(s21_floor(44.21), floor(44.21));
    ck_assert_ldouble_eq(s21_floor(22.11), floor(22.11));
    ck_assert_ldouble_eq(s21_floor(-21.21), floor(-21.21));
    ck_assert_ldouble_infinite(floor(INFINITY));
    ck_assert_ldouble_infinite(s21_floor(S21_INF));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("math_basic_functions_suite");
    TCase *tc1_1 = tcase_create("s21_fabs_test");
    TCase *tc1_2 = tcase_create("s21_fact_test");
    Suite *s2 = suite_create("math_fmod_suite");
    TCase *tc2_1 = tcase_create("s21_fmod_test");
    Suite *s3 = suite_create("math_power_suite");
    TCase *tc3_1 = tcase_create("s21_exp_test");
    TCase *tc3_2 = tcase_create("s21_log_test");
    TCase *tc3_3 = tcase_create("s21_pow_test");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, fabs_basic);
    tcase_add_test(tc1_1, fabs_inf);
    tcase_add_test(tc1_1, fabs_nan);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, fact_test);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, fmod_basic);
    tcase_add_test(tc2_1, fmod_basic_inf);
    tcase_add_test(tc2_1, fmod_nan);
    suite_add_tcase(s3, tc3_1);
    tcase_add_test(tc3_1, exp_basic);
    tcase_add_test(tc3_1, exp_inf);
    tcase_add_test(tc3_1, exp_nan);
    suite_add_tcase(s3, tc3_2);
    tcase_add_test(tc3_2, log_basic);
    tcase_add_test(tc3_2, log_inf);
    tcase_add_test(tc3_2, log_nan);
    suite_add_tcase(s3, tc3_3);
    tcase_add_test(tc3_3, pow_basic);
    tcase_add_test(tc3_3, test_s21_pow);
    tcase_add_test(tc3_3, test_s21_sqrt);
    tcase_add_test(tc3_3, test_s21_sin);
    tcase_add_test(tc3_3, test_s21_cos);
    tcase_add_test(tc3_3, test_s21_fmod);
    tcase_add_test(tc3_3, test_s21_ceil);
    tcase_add_test(tc3_3, test_s21_floor);

    srunner_add_suite(sr, s2);
    srunner_add_suite(sr, s3);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
