/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "/Users/igor/Coding/C/s21_math/src/check_test.check" instead.
 */

#include <check.h>

#include <check.h>
#include <math.h>
#include <stdlib.h>

#include "s21_math.h"

#define CHK_EPS 1e-6



START_TEST(abs_basic)
{

int testcases[] = {-2147483648, -2147483647, -422112, -3458,  -2,        -1, -0,
                   0,           1,           2,       481516, 2147483647};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_int_eq(s21_abs(testcases[i]), abs(testcases[i]));

}
END_TEST

START_TEST(fabs_basic)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      0.43,
                      -1e-10,
                      1e-4,
                      -4.2356e-2,
                      0.5,
                      -1.,
                      1.5,
                      -100.,
                      9.123123e6,
                      -1e4,
                      1e10,
                      S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_eq_tol(s21_fabs(testcases[i]), fabs(testcases[i]), CHK_EPS);

}
END_TEST

START_TEST(fabs_inf)
{

double testcases[] = {S21_INF, -S21_INF};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_infinite(s21_fabs(testcases[i]));

}
END_TEST

START_TEST(fabs_nan)
{

ck_assert_ldouble_nan(s21_fabs(S21_NAN));

}
END_TEST

START_TEST(fact_test)
{

int testcases[] = {1, 2, 5, 10};
int result[] = {1, 2, 120, 3628800};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_int_eq(s21_fact(testcases[i]), result[i]);

}
END_TEST


START_TEST(fmod_basic)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      1e-10,
                      1e-4,
                      4.2356e-2,
                      0.43,
                      0.5,
                      0.999999,
                      1.,
                      1.0000001,
                      1.001,
                      1.008888,
                      1.01,
                      1.1,
                      1.5,
                      100.,
                      9.123123e6,
                      1e4,
                      1e10,
                      S21_MAX_DOUBLE};

size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  for (size_t j = 0; j < n; ++j)
    ck_assert_ldouble_eq_tol(s21_fmod(testcases[i], testcases[j]),
                             fmod(testcases[i], testcases[j]), CHK_EPS);

}
END_TEST

START_TEST(fmod_inf)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      0.,
                      0.43,
                      1e-10,
                      1e-4,
                      4.2356e-2,
                      0.5,
                      1.,
                      1.5,
                      100.,
                      9.123123e6,
                      1e4,
                      1e10,
                      S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_eq_tol(s21_fmod(testcases[i], S21_INF),
                           fmod(testcases[i], S21_INF), CHK_EPS);

}
END_TEST

START_TEST(fmod_nan)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      0.,
                      0.43,
                      1e-10,
                      1e-4,
                      4.2356e-2,
                      0.5,
                      1.,
                      1.5,
                      100.,
                      9.123123e6,
                      1e4,
                      1e10,
                      S21_MAX_DOUBLE};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_nan(s21_fmod(testcases[i], 0));
  ck_assert_ldouble_nan(fmod(testcases[i], 0));
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, testcases[i]));
  ck_assert_ldouble_nan(fmod(S21_NAN, testcases[i]));
}

}
END_TEST


START_TEST(trunc_basic)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      0.,
                      1e-10,
                      1e-4,
                      4.2356e-2,
                      0.43,
                      0.5,
                      0.999999,
                      1.,
                      1.0000001,
                      1.001,
                      1.008888,
                      1.01,
                      1.1,
                      1.5,
                      100.,
                      9.123123e6,
                      1e4,
                      1e10,
                      S21_MAX_DOUBLE};

size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_eq_tol(s21_trunc(testcases[i]), trunc(testcases[i]),
                           CHK_EPS);

}
END_TEST

START_TEST(trunc_inf)
{

double testcases[] = {-S21_INF, S21_INF};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_infinite(s21_trunc(testcases[i]));
  ck_assert_ldouble_infinite(trunc(testcases[i]));
}

}
END_TEST

START_TEST(trunc_nan)
{

ck_assert_ldouble_nan(s21_trunc(S21_NAN));
ck_assert_ldouble_nan(trunc(S21_NAN));

}
END_TEST

START_TEST(floor_basic)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      0.,
                      1e-10,
                      1e-4,
                      4.2356e-2,
                      0.43,
                      0.5,
                      0.999999,
                      1.,
                      1.0000001,
                      1.001,
                      1.008888,
                      1.01,
                      1.1,
                      1.5,
                      100.,
                      9.123123e6,
                      1e4,
                      1e10,
                      S21_MAX_DOUBLE};

size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_eq_tol(s21_floor(testcases[i]), floor(testcases[i]),
                           CHK_EPS);

}
END_TEST

START_TEST(floor_inf)
{

double testcases[] = {-S21_INF, S21_INF};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_infinite(s21_floor(testcases[i]));
  ck_assert_ldouble_infinite(floor(testcases[i]));
}

}
END_TEST

START_TEST(floor_nan)
{

ck_assert_ldouble_nan(s21_floor(S21_NAN));
ck_assert_ldouble_nan(floor(S21_NAN));

}
END_TEST

START_TEST(ceil_basic)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      0.,
                      1e-10,
                      1e-4,
                      4.2356e-2,
                      0.43,
                      0.5,
                      0.999999,
                      1.,
                      1.0000001,
                      1.001,
                      1.008888,
                      1.01,
                      1.1,
                      1.5,
                      100.,
                      9.123123e6,
                      1e4,
                      1e10,
                      S21_MAX_DOUBLE};

size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_eq_tol(s21_ceil(testcases[i]), ceil(testcases[i]), CHK_EPS);

}
END_TEST

START_TEST(ceil_inf)
{

double testcases[] = {-S21_INF, S21_INF};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_infinite(s21_ceil(testcases[i]));
  ck_assert_ldouble_infinite(ceil(testcases[i]));
}

}
END_TEST

START_TEST(ceil_nan)
{

ck_assert_ldouble_nan(s21_ceil(S21_NAN));
ck_assert_ldouble_nan(ceil(S21_NAN));

}
END_TEST

START_TEST(round_basic)
{

double testcases[] = {-S21_MAX_DOUBLE,
                      -1e20,
                      -7.4143526437e3,
                      -3144.51e-4,
                      0.,
                      1e-10,
                      1e-4,
                      4.2356e-2,
                      0.43,
                      0.5,
                      0.999999,
                      1.,
                      1.0000001,
                      1.001,
                      1.008888,
                      1.01,
                      1.1,
                      1.5,
                      100.,
                      9.123123e6,
                      1e4,
                      1e10,
                      S21_MAX_DOUBLE};

size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i)
  ck_assert_ldouble_eq_tol(s21_round(testcases[i]), round(testcases[i]),
                           CHK_EPS);

}
END_TEST

START_TEST(round_inf)
{

double testcases[] = {-S21_INF, S21_INF};
size_t n = sizeof(testcases) / sizeof(testcases[0]);

for (size_t i = 0; i < n; ++i) {
  ck_assert_ldouble_infinite(s21_round(testcases[i]));
  ck_assert_ldouble_infinite(round(testcases[i]));
}

}
END_TEST

START_TEST(round_nan)
{

ck_assert_ldouble_nan(s21_round(S21_NAN));
ck_assert_ldouble_nan(round(S21_NAN));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("math_basic_functions_suite");
    TCase *tc1_1 = tcase_create("s21_abs_test");
    TCase *tc1_2 = tcase_create("s21_fabs_test");
    TCase *tc1_3 = tcase_create("s21_fact_test");
    Suite *s2 = suite_create("math_fmod_suite");
    TCase *tc2_1 = tcase_create("s21_fmod_test");
    Suite *s3 = suite_create("math_round_suite");
    TCase *tc3_1 = tcase_create("s21_trunc_test");
    TCase *tc3_2 = tcase_create("s21_floor_test");
    TCase *tc3_3 = tcase_create("s21_ceil_test");
    TCase *tc3_4 = tcase_create("s21_round_test");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, abs_basic);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, fabs_basic);
    tcase_add_test(tc1_2, fabs_inf);
    tcase_add_test(tc1_2, fabs_nan);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_3, fact_test);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, fmod_basic);
    tcase_add_test(tc2_1, fmod_inf);
    tcase_add_test(tc2_1, fmod_nan);
    suite_add_tcase(s3, tc3_1);
    tcase_add_test(tc3_1, trunc_basic);
    tcase_add_test(tc3_1, trunc_inf);
    tcase_add_test(tc3_1, trunc_nan);
    suite_add_tcase(s3, tc3_2);
    tcase_add_test(tc3_2, floor_basic);
    tcase_add_test(tc3_2, floor_inf);
    tcase_add_test(tc3_2, floor_nan);
    suite_add_tcase(s3, tc3_3);
    tcase_add_test(tc3_3, ceil_basic);
    tcase_add_test(tc3_3, ceil_inf);
    tcase_add_test(tc3_3, ceil_nan);
    suite_add_tcase(s3, tc3_4);
    tcase_add_test(tc3_4, round_basic);
    tcase_add_test(tc3_4, round_inf);
    tcase_add_test(tc3_4, round_nan);

    srunner_add_suite(sr, s2);
    srunner_add_suite(sr, s3);

    srunner_run_all(sr, CK_VERBOSE);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
